create database playstoreDB;
use playstoreDB;
select upper(Developername) from Developer;
select lower(Developername) from Developer;
select length(AppName) from Apps;
select CategoryName,length(CategoryName) from Categories;
select current_date(),current_time();
select round(Rating,0) from Apps;
select AppName,left(AppName,5) from Apps;
select Developername,Country from Developer;
select concat(Developername,' ',Country)from Developer;
select Rating from Apps;
select round(Rating,1) from Apps;
select ceil(Price) from Apps;
select year(FounderYear) from Developer;
select FounderYear from Developer;
select convert(Downloads,char) from Apps;
select AppName,Rating from Apps;
select left(CategoryName,3) from Categories;
select ABS(Price-200) from Apps;
select Developername,length(Developername) from Developer;
select current_time(),current_timestamp();
select convert(MinimumAge,char) from Categories;